<?php

namespace AppBundle\Repository;

/**
 * IntervenantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervenantsRepository extends \Doctrine\ORM\EntityRepository
{
}
