<?php

namespace AppBundle\Repository;

/**
 * ResponsablePedagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsablePedagoRepository extends \Doctrine\ORM\EntityRepository
{
}
